apiVersion: v1
kind: Service
metadata:
  name: surveyform-service
  labels:
    app: surveyform-springboot
spec:
  selector:
    app: surveyform-springboot  
  type: NodePort 
  ports:
    - port: 8080        
      targetPort: 8080   
      protocol: TCP
      name: http         
    - port: 443         
      targetPort: 443   
      protocol: TCP
      name: https        
